### ISSUE TITLE
Exercice 3 incorrect

### ISSUE THREAD

**Issue by tmagnier** [hogoww/reseauM#1]
Salut, 

Je crois que ton programme pour l'exercice 3 est incorrect. Je voulais proposer ma solution mais je ne suis pas collaborateur. Peux-tu m'ajouter en tant que tel ? 

Merci

**Comment by hogoww** [comment]
Je t'ajoute temporairement, mais pourrais-tu me dire pourquoi? Histoire de le corriger au minimum.
(Honnêtement j'ai pas fais particulièrement attention je les trouve pas très intéressant).

**Comment by hogoww** [comment]
Ya en effet 2/3 erreurs, mais je maintiens que la solution est valable.
